name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"

    - name: Greet new issue
      if: github.event_name == 'issues'
      run: echo "Hello @${{ github.event.issue.user.login }}! Thank you for opening an issue. We will get back to you shortly."

    - name: Greet new pull request
      if: github.event_name == 'pull_request'
      run: echo "Hello @${{ github.event.pull_request.user.login }}! Thank you for your pull request. We will review it soon."
